"""empty message

Revision ID: 0a3516ac47a0
Revises: 3dd3c2f5a8fe
Create Date: 2020-01-31 11:20:09.148099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a3516ac47a0'
down_revision = '3dd3c2f5a8fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('is_person_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_persons_is_person_active'), 'persons', ['is_person_active'], unique=False)
    op.drop_index('ix_persons_is_active', table_name='persons')
    op.drop_column('persons', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_persons_is_active', 'persons', ['is_active'], unique=False)
    op.drop_index(op.f('ix_persons_is_person_active'), table_name='persons')
    op.drop_column('persons', 'is_person_active')
    # ### end Alembic commands ###
