"""empty message

Revision ID: 1291e152529f
Revises: 1951c01cfbba
Create Date: 2020-01-27 15:29:53.265421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1291e152529f'
down_revision = '1951c01cfbba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_persons_email', table_name='persons')
    op.create_index(op.f('ix_persons_email'), 'persons', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persons_email'), table_name='persons')
    op.create_index('ix_persons_email', 'persons', ['email'], unique=True)
    # ### end Alembic commands ###
