"""empty message

Revision ID: 38df2a3bf51c
Revises: 1291e152529f
Create Date: 2020-01-27 15:59:05.421602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38df2a3bf51c'
down_revision = '1291e152529f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('facility', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'persons', 'facilities', ['facility'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persons', type_='foreignkey')
    op.drop_column('persons', 'facility')
    # ### end Alembic commands ###
