"""empty message

Revision ID: 76b7d09760f8
Revises: b3b890bd5c21
Create Date: 2020-02-06 22:32:30.218236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76b7d09760f8'
down_revision = 'b3b890bd5c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_constraint('persons_ibfk_1', 'persons', type_='foreignkey')
    op.create_foreign_key(None, 'persons', 'roles', ['role_id'], ['id'])
    op.drop_column('persons', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('role', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'persons', type_='foreignkey')
    op.create_foreign_key('persons_ibfk_1', 'persons', 'roles', ['role'], ['id'])
    op.drop_column('persons', 'role_id')
    # ### end Alembic commands ###
