"""empty message

Revision ID: b3b890bd5c21
Revises: 4570d39f129d
Create Date: 2020-02-02 13:09:46.322305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3b890bd5c21'
down_revision = '4570d39f129d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('persons_ibfk_2', 'persons', type_='foreignkey')
    op.drop_column('persons', 'facility')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('facility', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('persons_ibfk_2', 'persons', 'facilities', ['facility'], ['id'])
    # ### end Alembic commands ###
